import Foundation

/// What one copy held.
enum NookClipboardContent: Equatable, Sendable {
    case text(String)
    /// A copied picture: its data as it sat on the pasteboard, the type it
    /// came as, and a small PNG for the list.
    case image(data: Data, typeIdentifier: String, thumbnail: Data?)

    /// True when both hold the same copy. A picture is told by its data
    /// alone, never by its thumbnail.
    func isSameCopy(as other: NookClipboardContent) -> Bool {
        switch (self, other) {
        case let (.text(mine), .text(theirs)):
            return mine == theirs
        case let (.image(mine, _, _), .image(theirs, _, _)):
            return mine == theirs
        default:
            return false
        }
    }

    var imageByteCount: Int {
        if case let .image(data, _, _) = self { return data.count }
        return 0
    }
}

/// One copy kept in the clipboard history.
struct NookClipboardEntry: Identifiable, Equatable, Sendable {
    let id: UUID
    let content: NookClipboardContent
    let date: Date
}

/// Whether macOS lets the app read what other apps copied.
enum NookClipboardAccess: Equatable, Sendable {
    /// Reads go through without the user being asked.
    case allowed
    /// macOS puts up an alert for every read. The history stops reading
    /// on its own and waits for the user to ask.
    case asks
    /// Reads are refused.
    case denied
}

/// The last copies, newest first. Kept in memory only: nothing here is
/// Codable, and nothing writes it to disk or to a log.
struct NookClipboardHistory: Equatable, Sendable {
    static let maxEntries = 20
    /// Longer text is left out whole. A cut-off copy would paste wrong.
    static let maxTextBytes = 256 * 1024
    /// One picture larger than this is left out.
    static let maxImageBytes = 8 * 1024 * 1024
    /// All pictures together stay under this. The oldest ones go first.
    static let maxTotalImageBytes = 24 * 1024 * 1024
    static let previewLength = 160

    /// Marker types from nspasteboard.org. Password managers put them on
    /// the pasteboard beside a secret, and apps mark copies that are not
    /// meant to be kept the same way.
    static let secretTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// A copied file belongs in the tray's file list, not here. Its name
    /// alone would paste as text and not as the file.
    static let fileTypes: Set<String> = ["public.file-url", "NSFilenamesPboardType"]

    private(set) var entries: [NookClipboardEntry] = []

    /// True when a pasteboard carrying these types must not be read.
    static func shouldSkip(types: [String]) -> Bool {
        types.contains { secretTypes.contains($0) || fileTypes.contains($0) }
    }

    /// True when the copy is worth keeping and small enough to keep.
    static func accepts(_ content: NookClipboardContent) -> Bool {
        switch content {
        case let .text(text):
            return !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                && text.utf8.count <= maxTextBytes
        case let .image(data, _, _):
            return !data.isEmpty && data.count <= maxImageBytes
        }
    }

    /// One line for the list: runs of spaces and line breaks become one
    /// space, and a long copy is cut short.
    static func preview(of text: String) -> String {
        let words = text.split(whereSeparator: \.isWhitespace)
        let line = words.joined(separator: " ")
        guard line.count > previewLength else { return line }
        return String(line.prefix(previewLength)) + "…"
    }

    /// Puts a copy at the top. A repeat of a copy already in the list
    /// moves that one up and does not add a second row. Returns the entry
    /// now at the top, or nil when the copy was left out.
    @discardableResult
    mutating func record(_ content: NookClipboardContent, id: UUID = UUID(), date: Date = Date()) -> NookClipboardEntry? {
        guard Self.accepts(content) else { return nil }
        entries.removeAll { $0.content.isSameCopy(as: content) }
        let entry = NookClipboardEntry(id: id, content: content, date: date)
        entries.insert(entry, at: 0)
        trim()
        return entry
    }

    /// Gives a kept picture its small picture for the list. The copy is
    /// recorded first and drawn after, off the main thread, which is why
    /// the thumbnail arrives on its own. A row that has gone since is left
    /// alone.
    mutating func setThumbnail(_ thumbnail: Data?, for id: UUID) {
        guard let thumbnail,
              let index = entries.firstIndex(where: { $0.id == id }),
              case let .image(data, typeIdentifier, _) = entries[index].content else { return }
        let entry = entries[index]
        entries[index] = NookClipboardEntry(
            id: entry.id,
            content: .image(data: data, typeIdentifier: typeIdentifier, thumbnail: thumbnail),
            date: entry.date
        )
    }

    /// Moves an entry to the top, which is where a copy made again from
    /// the list belongs.
    mutating func moveToTop(_ id: UUID, date: Date = Date()) {
        guard let index = entries.firstIndex(where: { $0.id == id }) else { return }
        let entry = entries.remove(at: index)
        entries.insert(NookClipboardEntry(id: entry.id, content: entry.content, date: date), at: 0)
    }

    mutating func remove(_ id: UUID) {
        entries.removeAll { $0.id == id }
    }

    mutating func clear() {
        entries = []
    }

    private mutating func trim() {
        if entries.count > Self.maxEntries {
            entries.removeLast(entries.count - Self.maxEntries)
        }
        var imageBytes = entries.reduce(0) { $0 + $1.content.imageByteCount }
        while imageBytes > Self.maxTotalImageBytes,
              let oldest = entries.lastIndex(where: { $0.content.imageByteCount > 0 }) {
            imageBytes -= entries[oldest].content.imageByteCount
            entries.remove(at: oldest)
        }
    }
}
